{
 "title": "App Monitoring",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "{{container}}" }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}