name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-lint
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-test-app:latest .
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-test-app:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker-build-push
  #   steps:
  #     - uses: appleboy/ssh-action@v0.1.7
  #       with:
  #         host: ${{ secrets.STAGING_HOST }}
  #         username: ${{ secrets.STAGING_USER }}
  #         key: ${{ secrets.STAGING_SSH_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/devops-test-app:latest
  #           docker compose -f /path/to/docker-compose.yaml up -d
  #           unhealthy=$(docker inspect -f '{{.State.Health.Status}}' devops-test-app-app-1)
  #           if [ "$unhealthy" != "healthy" ]; then
  #             echo "Container unhealthy, rolling back..."
  #             docker image rm ${{ secrets.DOCKER_USERNAME }}/devops-test-app:latest
  #             docker compose -f /path/to/docker-compose.yaml up -d
  #             exit 1
  #           fi
