name: CI/CD Local

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npx eslint .
      - run: npm test

  docker-build-deploy:
    runs-on: self-hosted
    needs: build-lint
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t devops-test-app:latest .
      - run: |
          docker compose -f ./docker-compose.yaml up -d
          unhealthy=$(docker inspect -f '{{.State.Health.Status}}' devops-test-app-app-1)
          if [ "$unhealthy" != "healthy" ]; then
            echo "Container unhealthy, rolling back..."
            docker image rm devops-test-app:latest
            docker compose -f ./docker-compose.yaml up -d
            exit 1
          fi
